openapi: 3.0.0
info:
  title: Client's panel API docs Advertisers Dev API
  version: v5
  description: 'RTB House Client Panel REST API for managing advertisers, campaigns, product offers, audiences,

    RTB creatives, conversions, and accessing performance statistics. Supports campaign management,

    billing retrieval, and detailed analytics including RTB stats, win-rate stats, top hosts, and

    deduplication stats.


    Authentication scheme types:

    | Security Scheme Type      | HTTP   |

    | ------------------------- | ------ |

    | HTTP Authorization Scheme | Basic  |

    | HTTP Authorization Scheme | Bearer |

    '
servers:
- url: https://api.panel.rtbhouse.com/v5
security:
- basicAuth: []
- bearerAuth: []
tags:
- name: Dev
paths:
  /healthcheck:
    get:
      summary: Check server status
      tags:
      - Dev
      security: []
      responses:
        '200':
          description: Return SUCCESS string.
          content:
            application/json:
              schema:
                type: string
                example: SUCCESS
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    basicAuth:
      type: http
      scheme: basic
